export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',

  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',

  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',

  CLOSE_INVOICE = 'CLOSE_INVOICE',

  CREATE_VEHICLE = 'CREATE_VEHICLE',

  CHANGE_ROLE = 'CHANGE_ROLE',
}
